Repository cnr-ibba/nf-resequencing-mem, pull requests merged in 2024-03, with the labels that each got.

#61 :construction_worker: update linting workflows
  .github/workflows/linting.yml
  .github/workflows/linting_comment.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: bug, dependencies

#66 Issue 9.1
  subworkflows/local/prepare_genome.nf
  workflows/resequencing-mem.nf
Labels: bug

#67 :sparkles: Annotate VCF file with SnpEff
  CHANGELOG.md
  CITATIONS.md
  README.md
  assets/NO_FILE
  conf/modules.config
  conf/test.config
  modules.json
  modules/nf-core/snpeff/download/environment.yml
  modules/nf-core/snpeff/download/main.nf
  modules/nf-core/snpeff/download/meta.yml
  modules/nf-core/snpeff/download/snpeff-download.diff
  modules/nf-core/snpeff/snpeff/environment.yml
  modules/nf-core/snpeff/snpeff/main.nf
  modules/nf-core/snpeff/snpeff/meta.yml
  modules/nf-core/snpeff/snpeff/snpeff-snpeff.diff
  modules/nf-core/snpeff/snpeff/tests/main.nf.test
  modules/nf-core/snpeff/snpeff/tests/main.nf.test.snap
  modules/nf-core/snpeff/snpeff/tests/nextflow.config
  modules/nf-core/snpeff/snpeff/tests/tags.yml
  nextflow.config
  nextflow_schema.json
  subworkflows/local/snpeff_annotate.nf
  workflows/resequencing-mem.nf
Labels: enhancement

#68 :wrench: configure MultiQC analysis
  .vscode/settings.json
  assets/methods_description_template.yml
  assets/multiqc_config.yml
  conf/modules.config
  modules.json
  modules/nf-core/multiqc/environment.yml
  modules/nf-core/multiqc/main.nf
  modules/nf-core/multiqc/meta.yml
  modules/nf-core/multiqc/tests/main.nf.test
  modules/nf-core/multiqc/tests/main.nf.test.snap
  nextflow.config
  workflows/resequencing-mem.nf
Labels: bug, performance
